version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - aws s3 cp s3://your-bucket-name . --recursive
      - git clone -b branch-name https://github.com/owner/repo.git
      - aws s3 cp repo/ s3://your-bucket-name --recursive
