version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      # - aws s3 cp s3://gihub-deploy-890 . --recursive
      # - git clone -b aws_devops https://github.com/Devopsiac765/devopsmdktech.git
      # - aws s3 cp devopsmdktech/ s3://gihub-deploy-890 --recursive
            # Sync only the changed files to the S3 bucket
      - cd $CODEBUILD_SRC_DIR  # Navigate to the source directory provided by CodePipeline
      - ls
      # - git clone -b aws_devops https://github.com/Devopsiac765/devopsmdktech.git
      - aws s3 sync . s3://gihub-deploy-890/nellore --delete
