version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - aws s3 cp s3://gihub-deploy-890 . --recursive
      - git clone -b aws_devops https://github.com/Devopsiac765/devopsmdktech.git
      - aws s3 cp devopsmdktech/ s3://gihub-deploy-890 --recursive
